### ISSUE TITLE
Uue materjali loomisel saab kasutaja valida ainult H5P

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/kadaka-h5p#13]
+ tõlkida kirjeldus

![Screenshot 2019-12-02 at 10 21 39](https://user-images.githubusercontent.com/380007/69943038-b124b900-14ed-11ea-9438-1f27ebdba995.png)

**Comment by leoste** [comment]
see ongi juba nii, tavakasutajate "lisa sisu" nupp võtab kohe h5p lisamise akna lahti, teised valikud pole lubatud. admin kasutajad saavad rohkem sisutüüpe lisada.
