### ISSUE TITLE
Lehe logo ja pealkiri on klikatav, suunab esilehele

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/kadaka-h5p#17]

**Comment by leoste** [comment]
On juba klikatav. 
![image](https://user-images.githubusercontent.com/35530198/71816539-995fc800-308b-11ea-98b7-1ba683177371.png)
Kui aga sisse loginud kasutaja on admin, siis keele vahetaja ploki muutmise kast katab admini jaoks selle ära
![image](https://user-images.githubusercontent.com/35530198/71816567-b4323c80-308b-11ea-9f62-0930a2a35c81.png)
