### ISSUE TITLE
Õpilase vaade kuvab iFrame-i sama kõrgusega, mis brauseri aken (viewport)

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/kadaka-h5p#23]
**Hetkel:**

![Screenshot 2020-02-19 at 15 23 20](https://user-images.githubusercontent.com/380007/74840549-d926fa00-532f-11ea-9e00-52fac3009f0b.png)

**Vajalik:**

![Screenshot 2020-02-19 at 15 24 33](https://user-images.githubusercontent.com/380007/74840574-e2b06200-532f-11ea-9a7c-8aeac7f96de7.png)

**Comment by tammets** [comment]
Vt ka https://h5p.org/node/189352

**Comment by leoste** [comment]
bug mõnede sisutüüpidega
