### ISSUE TITLE
lisada keele valik, umbes nagu edidaktikumis

### ISSUE THREAD

**Issue by leoste** [centre-for-educational-technology/kadaka-h5p#4]
![image](https://user-images.githubusercontent.com/35530198/68209398-f8498800-ffdb-11e9-9bc3-ac444634c02f.png)

**Comment by tammets** [comment]
Kuvada keele valik peamenüüs. Vaikimisi keel = vene keel

![Screenshot 2019-11-12 at 10 12 59](https://user-images.githubusercontent.com/380007/68653887-64c10b80-0535-11ea-88c7-fdb066b99355.png)

**Comment by tammets** [comment]
+ eemaldada keele valik parema paani pealt.

**Comment by leoste** [comment]
liigutasin üles selle
